name: Publish all font packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all packages
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            font-packages

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish all packages
        run: |
          count=0
          for package in font-packages/*; do
            if [ -d "$package" ]; then
              echo "Publishing package: $(basename $package)"
              if [ $((count % 2)) -eq 0 ]; then
                export NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}
              else
                export NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN_2 }}
              fi
              (cd "$package" && npm publish --access public)
              count=$((count + 1))
            fi
          done
